### ISSUE TITLE
Exception, Error DTO 수정사항

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#211]
앱이 언어 설정을 지원할 것 이므로 현재 Exception DTO의 내용이 영어 또는 한국으로 지원할 수 있어야합니다

**Comment by chocojaem** [comment]
아 그리고 여유가 되시면 문구를 좀 더 부드럽고 세부적으로 수정해주시면 감사하겠습니다!

**Comment by won983212** [comment]
넵. 영어 메시지도 추가하겠습니다.

언어 메시지를 받기 위해서는 요청에 아래 Header를 추가해야합니다.
```
# 한국어
Accept-Language : ko-KR

# 영어 (생략 가능)
Accept-Language : en-US
```

**Comment by won983212** [comment]
## 설계 Note
@YOONSEOUNGHWAN 
 - 영어 메시지를 추가하기 위해서는 `messages_en.properties`와 `errors_en.properties`를 추가해야합니다. 이 파일에 영어 메시지들을 기입하면 됩니다.
 - 기존에 쓰던 한글로 된 메시지 파일들은 이름에 ko를 붙여야 합니다.
   - `messages.properties` -> `messages_ko.properties`
   - `errors.properties` -> `errors_ko.properties`
