### ISSUE TITLE
게시판 DTO createdAt 수정 요청

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#219]
청원 게시판을 포함한 자유게시판 단건 조회시 2022/04/02 18:32 형식으로 부탁드리고 게시판 리스트 조회 시에도 통일해서 주세요! substring은 제가 하겠습니다.

**Comment by chocojaem** [comment]
+ 앞으로 게시판 이용시에 몇분전 몇시간 전 이런식으로 표기 되어야 하는데 현재 방식으로는 불가능합니다. 또한 게시물 뿐만 아니라 코멘트도 마찬가지로 되어야합니다.

**Comment by won983212** [comment]
'n분 전'은 오늘 처음 듣는 이야기네요. 우선 기존 디자인에 앱이 추가되면서 생긴 문제인 것 같고, 시각까지 표시하겠습니다.

Post/Comment의 생성 날짜는 아래로 통일됩니다.

```
yyyy-MM-dd HH:mm:ss
```
