### ISSUE TITLE
댓글 DTO 수정

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#220]
현재 자유게시판의 모든 댓글의 auther가 익명으로 되어 있는데 이것도 학과 닉네임으로 분리해서 전송되어야 합니다! 청원게시판은 그대로 익명입니다

**Comment by won983212** [comment]
**자유게시판**만 수정됩니다.
익명 -> 닉네임과 학과

**Comment by developerChans** [comment]
DTO 수정 Response swagger 적용완료되었을까요?
당장 적용안될 것 같다면, issue에 우선 Response 만 적어주셔도 좋습니다.

**Comment by won983212** [comment]
개발 서버에 반영했습니다
