### ISSUE TITLE
자유게시판 도배 방지 시간 제한 사라짐

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/student-council-homepage-backend#235]
제곧내

해당 부분들 벡엔드 문제 일 수 있음

**Comment by developerChans** [comment]
도배 방지기능
자유게시판: 3분에 한번 게시글 작성 가능.
이부분은 벡엔드에서 Message도 같이 Response에 담아 전달해야함

**Comment by chocojaem** [comment]
도배 방지기능은 대부분 프론트단에서 처리할 수 있습니다. 물론 백엔드에서도 처리하면 좋지만 앱의 경우 버튼의 쿨타임이 1초로 제한되어 있습니다.

**Comment by developerChans** [comment]
원래 이전에 3분으로 제한되어있던 기능입니다.

**Comment by won983212** [comment]
게시 쿨타임 3분으로 지정하겠습니다. (향후 쉽게 변경 가능)
