### ISSUE TITLE
회원탈퇴

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/student-council-homepage-backend#239]
회원 탈퇴 시 6개월 뒤에 사용자 정보 삭제
 - 6개월 전에는 계정이 삭제된 걸로 간주하도록
 - 6개월 지난 뒤에는 계정이 DB에서 완전히 삭제되도록.
   - 삭제시에는 관련된 DB Table 데이터도 모두 바꾸어야 한다.

탈퇴한 사용자는 (탈퇴한 사용자)로 표시되도록

**Comment by developerChans** [comment]
개인정보 수집 및 이용에 대한 동의를 받은 회원이 회원 탈퇴를 요청한 경우라면, 회원의 개인정보는 회원탈퇴와 동시에 즉시 파기하는 것이 원칙입니다. 그러나 몇 가지 예외적인 경우에는 일정 기간 동안 개인정보를 보관할 수 있습니다. 대표적인 예외사항으로는 다음과 같습니다.

관계법령에 의한 경우: 예를 들어, 상법, 계약법, 소비자보호법 등 다른 법령에서 개인정보를 보관하도록 규정한 경우에는 해당 법령에 따라 일정 기간 동안 개인정보를 보관할 수 있습니다.

분쟁 조정 및 해결을 위한 경우: 회원과 회사 간의 분쟁이 발생한 경우, 해당 분쟁의 해결을 위해 일정 기간 동안 개인정보를 보관할 수 있습니다.

부정 이용 방지 및 보안을 위한 경우: 회원이 부정 이용이나 불법 행위를 한 경우, 해당 사실을 조사하기 위해 일정 기간 동안 개인정보를 보관할 수 있습니다.

이용약관 위반 등에 대한 조치를 취하기 위한 경우: 회원이 이용약관을 위반하는 등 회사가 제공하는 서비스 이용규정에 위반한 경우, 이를 방지하고 규정 준수를 유도하기 위해 일정 기간 동안 개인정보를 보관할 수 있습니다.

이와 같은 예외사항은 개인정보처리방침이나 이용약관에서 명시되어야 하며, 명확한 법적 근거가 있어야 합니다. 또한, 해당 예외사항에 대한 보유기간도 적절하게 결정되어야 하며, 기간이 만료된 경우에는 즉시 파기되어야 합니다.

**Comment by developerChans** [comment]
회원탈퇴 후 유저정보는 6개월간 보관하기로 하며, 회원탈퇴될 경우, 게시글 댓글을 적은 useridx를 회원탈퇴된 유저로 useridx로 update한다.
또한, update 이전에 데이터는 바뀐 경우는 파일로 저장하되 내용은 다음과 같다.
제목: {삭제날짜}_{useridx}_{학번} 이며 파일 내에는,
update된 게시글 idx 들과, update 된 댓글 idx 목록을 순차적으로 모아서 파일로 따로 업데이트 하는 식으로 저장

+ 회원탈퇴 후 몇개월이내에는 다시 회원가입시도시 어떻게 할 것인지
+ 회원 삭제된 경우에는 다시 가입 할 수 있는지

회의

**Comment by won983212** [comment]
## 회원 탈퇴 기능 정리

- 회원 탈퇴 시 바로 delete하지 않고, 상태만 바꿉니다. (UserStatus를 `INACTIVE`로)
- 회원가입시 같은 studentId에 상태가 `INACTIVE`인 회원이 있다면, 새로 추가하지말고 그 회원 데이터를 수정해야합니다.
  - 상태=ACTIVE, 폰번호, 비밀번호, 이름 업데이트
- 회원 조회시 INACTIVE인 회원은 조회되지 않도록 해야합니다.
  - UserRepository에서 `findById`(상속), `findByStudentId`, `findByPhone`, `findByNickname`은 JPQL을 사용해서 ACTIVE상태인 User만 조회되도록 해야합니다.
- 6개월이 지나면 회원을 삭제하도록 Scheduler를 짜야합니다. (com.dku.council.domain.batch 패키지 참고)
  - 6개월이란 기간은 properties에서 언제든 조정할 수 있게 해야합니다.
  - 대충 매일 00시마다 탈퇴 기간이 6개월 지난 회원을 탐색해서 삭제하면 될 것 같습니다.
- Foreign key가 걸려있어서 그냥 삭제는 안됩니다.
  - 그래서 `탈퇴한 회원`이라는 더미 회원을 DB에 미리 넣어두고, 작성했던 글이나 댓글 등을 `탈퇴한 회원`으로 바꿔치기 해야합니다.
  - `탈퇴한 회원`은 User DB에 ID가 0인 user로 추가할 수 있습니다. (ID=0은 예시입니다. 다른 ID로 하셔도 됩니다.)
  - 회원은 Foreign key가 복잡하게 얽혀있어서 삭제가 어려우니, 우선 개인 정보만 지우는 것으로 하겠습니다. (password, name, phone을 빈 값으로 설정)
