### ISSUE TITLE
관리자 페이지

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/student-council-homepage-backend#240]
- 게시글 신고 누적 n회 이상 게시글 모아보기 + 삭제 블라인드(청원게시판, 자유게시판, VOC  게시판)
- 배너 삭제, 순서, 등록
- ~~배너 Performance(조회 수, 클릭 수, 호출 수)~~

**Comment by won983212** [comment]
+ 관리자는 회원 목록을 실명없이 볼 수 있어야하며, 정지, 삭제 권한이 있다.

**Comment by developerChans** [comment]
실명...은 안되고 닉네임까지만 될 것 같습니다.

**Comment by developerChans** [comment]
4월 23일까지 관리자 페이지 고우

**Comment by won983212** [comment]
배너 Performance는 Google Analytics에서 볼 수 있을 것 같습니다. 관리자 페이지에서는 우선 빼두겠습니다.

**Comment by developerChans** [comment]
4.24일 관리자페이지 최종 정리

1. 관리자는 회원 목록을 볼 수 있다. 해당 회원목록에서 정지 권한이 있다. (삭제는 회원탈퇴가 확실하게 정해지고 갑시다.)
2. 해당페이지에서 회원 목록을 클릭하였을때 해당 회원이 작성한 글들과 작성한 댓글이 있는 게시글들이 최신순으로 목록이 나오며, 해당 글을 눌럿을 시에 게시글 내용을 볼 수 있으며, 댓글 삭제 또는 게시글 블라인드 처리가 가능하다.
3. 관리자는 블라인드 된 게시글을 볼 수 있다.(해당 페이지 내에서 전체, 청원게시판, 자유게시판, QnA 게시판 으로 버튼) 또한, 각 목록에서 신고횟수가 몇번인지, 보여줘야함.
4. 해당 페이지에서는 게시글 제목들이 최신순으로 나오며, 해당 글을 누를 경우 내용이 뭔지 나오며, 블라인드 해제 또는 게시글 삭제가 가능하다.
5. 관리자는 삭제된 게시글을 볼 수 있다. (해당 페이지 내에서 전체, 청원게시판, 자유게시판, QnA 게시판 으로 버튼)
6. 해당 페이지에서는 게시글 제목들이 최신 순으로 나오며 해당 글을 누를 경우 내용이 뭔지 나온다. 삭제 해제만 가능하다.
7. 태그 추가/삭제/수정 이 가능하다
8. 대여물품 추가/삭제/수정, 대여물품 현황 삭제 가 가능하다.
9. 배너 삭제와 추가, 순서를 조정이 가능하며, 각 배너에 달릴 링크를 같이 추가하거나 같이 수정한다.


추후에 진행
1. 신고 n 회 이상된 글은 자동으로 신고 누적으로 블라인드 처리된 게시글로 처리한다.

**Comment by won983212** [comment]
> 관리자는 블라인드 된 게시글을 볼 수 있다.

현재 관리자는 굳이 관리자 페이지를 가지 않아도 블라인드된 글을 볼 수 있습니다. 이건 프론트에서 목록 API받고 판단해서 블라인드된 게시글인 경우에는 `블라인드 해제` 등의 버튼이 보이도록 하면 좋을 것 같습니다.

> 신고 n 회 이상된 글은 자동으로 신고 누적으로 블라인드 처리된 게시글로 처리한다.

현재 이미 적용되어있는 기능입니다. 5회 이상 신고가 누적될 경우 자동으로 blind됩니다. (5회라는 수치는 쉽게 바꿀 수 있습니다.)

**Comment by developerChans** [comment]
근데 또 블라인드된 게시글들을 관리자 페이지에서 모아보는것도 좋지 않을까요?

**Comment by won983212** [comment]
따로 모아 보는 것도 좋은 아이디어네요! 참고하겠습니다.

**Comment by YOONSEOUNGHWAN** [comment]
@developerChans 
> 배너 삭제와 추가, 순서를 조정이 가능하며, 각 배너에 달릴 링크를 같이 추가하거나 같이 수정한다.
- 현재 배너추가가 어떻게 되는지 알아야 합니다.  > 순서를 조정하는 로직에 대하여 알아봐야합니다.
- 해당 배너 페이지에서 단순 url 정보만 보여줄 지, 해당 url의 이미지를 보여 줄 지 > 만약 이미지를 보여준다면, 추후에 작성해야 할 것 같습니다. rendering 등의 학습 필요
