### ISSUE TITLE
일반 페이지에서의 관리자인지 아닌지 알려주는 API

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/student-council-homepage-backend#241]
총학소식, 회칙, 회의록 작성시엔 관리자만이 작성 할 수 있다. 따라서 관리자인지 아닌지 알려주는 API를 통해 구분해줘야한다.

**Comment by won983212** [comment]
Duplicate of #243 

동일하게 `/user`에서 관리자 여부를 확인할 수 있게 할 예정입니다.
