### ISSUE TITLE
Login, User DTO 문제점

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#245]
기존의 User 정보를 가져오는 DTO를 수정 하였지만 여전히 문제점이 있습니다. 
자동 로그인을 위해서는 토큰을 발급받은 후 해당 토큰으로 user 정보를 가져와 로그인 모델의 정보를 채워야하는데, 로그인 DTO는 admin 여부를 반환하는 반면 user을 통해 가져오는 정보는 admin 여부를 반환하지 않습니다. 
따라서 Login과 User 정보를 가져오는 DTO는 통일 되어야하며 둘다 admin 여부를 반환해야 합니다.

**Comment by won983212** [comment]
내부에서만 사용하는 object라면 몰라도, 외부에 노출되는 DTO는 기본적으로 공통화(통일)를 피하는 게 좋습니다.
 - 언제든 도메인이나 비즈니스 로직이 바뀌면서 공통성이 깨질 수 있기 때문입니다. 
 - 작은 변화가 다른 여러 dto에 영향을 줄 수 있습니다. 테스트를 작성했다면 큰 문제는 없겠지만, 위험요소가 될 수 있습니다.

그렇다고 공통화를 반드시 지양해야한다는 뜻은 아닙니다. 재사용성을 높인다는 관점에서 공통화는 유용할 수 있지만, 반대로 유연함은 줄어들 수 있습니다. (결국 프로젝트 특성에 따라 trade-off) 특히 도메인 기획이 자주 바뀌는 개발 단계의 우리 프로젝트에서는 더 주의가 필요할 것 같습니다.

지금 로그인 API와 유저 정보 API는 유사한 유저 응답 형태를 띠고 있긴합니다. 하지만 향후 로그인과 유저 정보 api를 통한 정보 제공의 범위가 달라질 가능성이 있습니다. (이는 즉 공통성이 깨짐을 의미)

따라서 이를 해결하기 위해 로그인 API에서도 제공하던 사용자 정보를 모두 `/user`로 옮기기로 했습니다. 이렇게 하면 유연함과 재사용성을 모두 챙길 수 있습니다.

### 예상 로그인 응답
```json
{
  "accessToken": "string",
  "refreshToken": "string"
}
```

### 예상 내 정보 조회 응답
```json
{
  "studentId": "학번",
  "username": "이름",
  "nickname": "닉네임",
  "yearOfAdmission": "입학년도",
  "major": "전공",
  "department": "단과대",
  "admin": false
}
```
