### ISSUE TITLE
청원 게시판 동의 현황에 대한 DTO 수정

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#247]
<img width="408" alt="Screenshot 2023-04-08 at 8 57 26 PM" src="https://user-images.githubusercontent.com/91131509/230719821-85cdd8f6-e3db-4653-807d-54ce7647c50e.png">
기존 청원 게시판의 동의 현황의 경우 총 4개 학과와 + 그외로 구성되므로 청원 게시판 DTO statisticList를 모든 학과를 던져주는 것에서 4개학과 명과 + 그외로 수정해야합니다.

**Comment by chocojaem** [comment]
![Screenshot 2023-04-09 at 1 30 21 PM](https://user-images.githubusercontent.com/91131509/230754444-6a6aeb28-4ce7-4b40-a527-c8d9d202556f.png)
또한 청원게시판 리스트 형태의 DTO의 경우 단건조회와 같이 TAG를 함께 주어야 합니다.

**Comment by won983212** [comment]
### 정리
 - 학과 4개까지만 표시하고, 5번째부터는 합산해서 '_기타_'로 표시
 - 청원게시판 리스트 조회시 TAG도 함께 포함
