### ISSUE TITLE
청원 게시글 삭제 안되는 버그

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#250]
청원 게시글의 DTO mine이 true인데도 불구하고 delete 요청시 해당 권한이 없습니다가 반환됩니다.

**Comment by YOONSEOUNGHWAN** [comment]
@chocojaem 청원 게시글은 관리자만 삭제할 수 있는 것 아니였나요?

**Comment by won983212** [comment]
청원 게시판은 작성자 포함, 운영자도 삭제할 수 없도록 기획되어있습니다.

지금은 **운영자만 삭제** -> **운영자도 삭제할 수 없게** 수정해야겠네요.

운영자도 삭제는 안되지만 **블라인드**는 가능합니다.
