### ISSUE TITLE
청원 게시글 단건 조회 버그

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#263]
청원 게시글의 답변이 등록된 글을 단건조회할 경우 다음과 같은 오류가 발생합니다
{"timestamp":"2023-04-10T19:36:58.305651","trackingId":"ab7ef6f2-4546-4fc8-b8c0-d505750c8a4a","status":"FORBIDDEN","code":"NotGrantedException","message":["Access denied."]}

**Comment by won983212** [comment]
※ Redis 캐시 이전 버전 호환 문제
