### ISSUE TITLE
티켓팅 기능

### ISSUE THREAD

**Issue by won983212** [EveryUniv/student-council-homepage-backend#287]
### 티켓팅
 - 축제(17일, 18일) 스텐드석 티켓팅을 진행한다.
 - 재학중인 단국대학교 학생만 신청할 수 있다.
 - 매크로 방지가 있어야 한다. (captcha)
 - 1인 1티켓.
 - 자리가 꽉 차면 예비 번호 필요.

### 티켓팅 일정
- **17일 축제**: 5월 13일 12시 (1200명)
- **18일 축제**: 5월 13일 18시 (1200명)

**Comment by developerChans** [comment]
Frontend 단에서 티켓팅하는 티켓이 날짜가 맞는지 확인하는 체크박스 만들기

티켓팅은 모든 사람에게 번호를 발급

**Comment by won983212** [comment]
- 여러번 dump할 경우 turn이 초기화되는 문제

**Comment by developerChans** [comment]
Ticketing Test API 관련 요청사항

17일차 티켓팅: 12일 20시 10분 부터 진행
18일차 티켓팅: 12일 20시 20분 부터 진행

"재학" 상태만 가능함
캡챠도 넣어져 있으면 좋겠음

각 사람은 각 일에 1개씩 티켓팅이 가능함.

**Comment by won983212** [comment]
> "재학" 상태만 가능함

'재학'이 아닌 회원이 티켓팅을 시도했을 때 잘 막아지는지 테스트해주세요.

> 캡챠 검증도 진행하면 좋겠음

현재는 테스트를 위해 꺼두고, 캡챠는 12일 당일 켜두겠습니다. 당일날 틀린 캡챠 입력 시 잘 막히는지 테스트해주세요.

> 각 사람은 각 일에 1개씩 티켓팅이 가능함.

마찬가지로 동일한 사람이 같은 이벤트에 대해 1회이상 티켓팅이 잘 막히는지 테스트해주세요.

주의할 점은 DB에 Dump하면, 또 신청할 수 있다는 점입니다. (성능을 위한 trade-off입니다. 혹시 중복 신청을 누군가 했더라도, 나중에 자체 중복 필터링해서 신청자 목록을 드릴거라 문제는 없습니다.) 그래서 가능한 db 덤프는 나중에 할 수록 좋습니다.

**Comment by developerChans** [comment]
17일차 티켓팅: 12일 20시 10분 부터 20시 20분까지 진행 
18일차 티켓팅: 12일 20시 20분 부터 20시 30분까지 진행

티켓팅 시간 이전엔 기존 그대로 message 
티켓팅 시간 이후 message: 많은 신청으로 티켓팅이 조기 마감되었습니다.(현재 티켓 검수 중 입니다.) 추후 문자로 알려 드리겠습니다.

실제 main API 마감시간
17일차 티켓팅: 12일 12시 00분 부터 17시 30분까지 진행 17시 30분 ~ 18시 00분 까지 인원보고 dump 할 지 말지 결정
18일차 티켓팅: 12일 20시 20분 부터 23시 59분까지 진행 24시 00분 ~ 24시 30분 까지 인원보고 dump 할 지 말지 결정

만약 티켓팅이 미달일 경우... 14일에도 한번 더 열거나, dump하지않고, 마감기한을 늘릴 수 있을 것 같음
