### ISSUE TITLE
티켓팅 발급 정보 확인 기능

### ISSUE THREAD

**Issue by won983212** [EveryUniv/student-council-homepage-backend#311]
온라인으로 발급 받은 티켓은 실물 티켓 (종이 팔찌 형태)로 바꾸어야 한다.

### 실물 티켓 발급 절차
1. 앱 티켓 화면의 QR코드를 보여준다.
2. 발급자는 이 QR코드를 찍는다.
   - 학번, 학과, 이름 정보를 볼 수 있다.
   - 동시에 인증 번호를 담은 SMS가 티켓 신청자 휴대폰으로 전송된다.
   - 발급자는 그 인증 번호도 볼 수 있다.
3. SMS를 받은 신청자는 '구두로' 발급자에게 신청 번호를 불러준다.
4. 발급자는 인증 번호가 맞는지 확인하고, 앱에서 발급 처리 후(발급 버튼 클릭), 실물 티켓을 지급한다.
5. 이후 추가적인 인증을 수행한다. (신분증 인증 등)

### 입장 절차
1. 앱으로 티켓을 보여주고, QR을 찍어 발급 여부/사용자 정보 등을 확인한다.
2. 실물 티켓과 신분증으로 추가 검증 후 입장.

**Comment by developerChans** [comment]
3번에서 문자 재전송이 가능하다.
5 이후, 실수로 발급버튼을 누르는 것에 대비하여, QR위의 ticket_id 또는 학번을 통해 발급 상태를 되돌릴 수 있어야한다. 이는 관리자 페이지에 추가하면 좋을듯요

**Comment by won983212** [comment]
### 필요한 API (아래는 예상 API입니다. 바뀔 수 있습니다.)
#### 변수
 - `ticketId`: 티켓의 ID (개인별로 가지고 있는 티켓)
 - `eventId`: 티켓팅 이벤트의 ID

#### 관리자용 API
 - `GET /ticket/{ticketId}`
   - **티켓 정보를 조회합니다.**
   - **응답**: 이름, 학과, 학번, 발급 여부, 예매 번호, SMS 인증번호
   - 동시에 티켓이 아직 발급되지 않았다면, SMS가 전송됩니다.
 - `POST /ticket/{ticketId}/sms`
   - **티켓 본인 인증용 SMS를 재전송합니다.**
   - **응답**: 바뀐 SMS인증 번호
   - 티켓 정보를 조회하면 자동으로 전송되지만, 문제가 발생하면 이 API를 사용해 직접 재전송할 수도 있습니다.
 - `POST /ticket/{ticketId}/permit`
   - **티켓 발급처리합니다.**
   - **응답**: 성공시 `{"message": "ok"}`
   - 티켓이 **발급**된 티켓으로 바뀝니다. 중복 발급을 막고, 입장시 확인을 위해 실물 티켓을 발급했다는 의미로 사용합니다.
 - `DELETE /ticket/{ticketId}/permit`
   - **티켓을 미발급처리합니다.**
   - **응답**: 성공시 `{"message": "ok"}`
   - 발급 처리된 티켓을 다시 미발급으로 바꿉니다. 실수나 정책 변경 사항으로 인해 발급한 경우 다시 취소할 수 있습니다.

#### 사용자용 API
 - `GET /ticket/event/{eventId}`
   - **특정 이벤트에 신청해서 발급받은 내 티켓 정보를 조회.**
   - 이름, 학과, 학번, 발급 여부, 예매 번호를 조회합니다.

### 추가 정보
 - 모든 ID는 **정수**이며, `1 ~ 9,223,372,036,854,775,807` 사이의 값을 가질 수 있습니다. 실제로는 백만 이하의 범위를 사용할 것 같습니다.
