### ISSUE TITLE
유저 정보에서 내가 쓴 글 불러올 때 문제점

### ISSUE THREAD

**Issue by chocojaem** [EveryUniv/student-council-homepage-backend#333]
현재 유저 정보에서 내가 쓴 글을 불러오면, 닉네임이 변경된 경우 글이 옛날 닉네임인 채로 남겨져 있습니다. 이 경우 다른 사용자가 해당 닉네임으로 변경할 경우 오해의 소지가 있으므로 모든 글들의 author은 닉네임이 변경될 경우 해당 닉네임으로 함께 변경되어야 합니다.

**Comment by won983212** [comment]
닉네임은 실시간으로 반영됩니다. 청원게시판은 "공과대학"으로, 자유게시판은 닉네임으로 표시되는데 이 문제인 것 같습니다.

이 부분은 그대로 청원게시판은 단과대 이름으로, 자유게시판은 닉네임으로 보이는 게 맞다고 봅니다.
 - 둘 다 닉네임으로 통일하면 청원 게시판 글 작성자의 닉네임을 볼 수 있다.
 - 단과대 이름으로 통일하면 자유게시판 작성자의 단과대를 알 수 있다.
 - 사실 내 글 보기이므로 작성자 정보는 크게 중요하지 않다. (나만 볼 수 있으며, 내가 작성한 글이 명백하므로)
