### ISSUE TITLE
현재시각과 지정한 시간과 비교하여 bool 값을 return하는 API

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/student-council-homepage-backend#352]
GET: 특정 날짜와 시간을 지정할시, API를 호출하였을때 특정 날짜와 시간보다 전일 경우 FALSE, 후일경우 TRUE를 잔환하는 API(모든 유저 가능)

UPDATE: 특정 날짜와 시간을 변경할 수 있는 API(관리자 권한)

**Comment by won983212** [comment]
어디에 쓰는 API인가요?

**Comment by developerChans** [comment]
아마 축제 기간동안 티켓팅 페이지를 들어갈때 사용할 것 같습니다.
