### ISSUE TITLE
[리펙토링 의견] 티켓팅과 귀향버스와 같은 경우 domain 내에 event라는 package로 묶는 것은 어떨지... 

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/student-council-homepage-backend#406]
event 폴더 내에서 ticketing과 homecomingbus? 이런 느낌으로 또 package를 나누는 것은 어떤지, 여러 관점에서 의견 부탁드립니다.

**Comment by won983212** [comment]
좋은 아이디어인 것 같습니다. 다만 멀티모듈 프로젝트로 구성할 예정이라 모듈 단위로 도메인을 나눌 것 같습니다.
